title: RSTLNE.org
description: > # this means to ignore newlines until "show_excerpts:"
  Vendor Neutral
  Operating System Independent
  Free and Open Source

show_excerpts: false # set to true to show excerpts on the homepage

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: jekyll-theme-dinky 

#plugins:
# - jekyll-feed
# - jekyll-seo-tag
